services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=t3
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"   # HDFS NameNode UI
    volumes:
      - hadoop_name:/hadoop/dfs/name
      - ./:/workspace
    networks: [ds]

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"   # HDFS DataNode UI
    volumes:
      - hadoop_data:/hadoop/dfs/data
    depends_on: [namenode]
    networks: [ds]

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "8088:8088"   # YARN RM UI
    depends_on: [namenode, datanode]
    networks: [ds]

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8088
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "8042:8042"   # YARN NM UI
    depends_on: [resourcemanager]
    networks: [ds]

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8088
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "8188:8188"   # MR JobHistory UI
    depends_on: [resourcemanager]
    networks: [ds]

volumes:
  hadoop_name:
  hadoop_data:

networks:
  ds:
